apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: web-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: celery-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      nodeSelector:
        role: workers
      containers:
        - name: celery-worker
          image: xoodb/web_django:latest
          imagePullPolicy: IfNotPresent
          command: 
            - 'celery'
            - '-A'
            - 'config'
            - 'worker'
            - '--loglevel=INFO'
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_URL
              value: redis://redis-service:6379/
          resources: {}
      restartPolicy: Always
status: {}
