installCRD: true

controller:
  replicas: 1
  nodeSelector: { role : builders }

repoServer:
  replicas: 1
  nodeSelector: { role : builders }
dex:
  nodeSelector: { role : builders }
server:
  replicas: 1
  nodeSelector: { role : builders }
  service:
    type: NodePort
    namedTargetPort: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: <AWS ACM arn>
      alb.ingress.kubernetes.io/tags: Environment=dev,Name=argocd-alb
  extraArgs:
    - --insecure
  config:
    accounts.admin: apiKey, login

  rbacConfig:
    policy.default: role:readonly

redis:
  enabled: true
  nodeSelector: { role : builders }

redis-ha:
  enabled: false