alertmanager:
  nodeSelector: { role : builders }

prometheus:
  nodeSelector: { role : builders }

grafana:
  defaultDashboardsTimezone: Asia/Seoul
  adminPassword: prom-operator
  nodeSelector: { role : builders }
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: <AWS ACM arn>
      alb.ingress.kubernetes.io/tags: Environment=dev,Name=grafana