apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: web-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: redis
  template:
    metadata:
      labels:
        pod: redis
    spec:
      nodeSelector:
        role: workers
      containers:
        - image: redis:latest
          imagePullPolicy: IfNotPresent
          name: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379